name = "DaggerGPU"
uuid = "68e73e28-2238-4d5a-bf97-e5d4aa3c4be2"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.1.6"

[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MemPool = "f9f48841-c794-520a-933b-121f7ba6ed94"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
CUDAExt = "CUDA"
MetalExt = "Metal"
ROCExt = "AMDGPU"

[compat]
AMDGPU = "0.4"
Adapt = "1, 2, 3"
CUDA = "3, 4"
Dagger = "0.17"
KernelAbstractions = "0.9"
MemPool = "0.3, 0.4"
Metal = "0.3, 0.4"
Requires = "1"
julia = "1.7"
