name = "DaggerGPU"
uuid = "68e73e28-2238-4d5a-bf97-e5d4aa3c4be2"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.1.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Adapt = "1, 2"
Dagger = "0.10.0"
KernelAbstractions = "0.4, 0.5"
Requires = "1"
julia = "1"

[extras]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AMDGPU", "CUDA", "Distributed", "Test"]
